name: Generate Release Notes
description: Generate release notes content for a release
branding:
  icon: align-justify
  color: white
inputs:
  tag:
    description: The tag name for the release. This can be an existing tag or a new one.
    required: true
    default: ${{ github.ref_name }}
  base:
    description: The name of the previous tag to use as the starting point for the release notes. Use to manually specify the range for the set of changes considered as part this release.
    required: false
  token:
    description: Github Token
    required: true
    default: ${{ github.token }}
  repository:
    description: Repository to create the release for
    required: true
    default: ${{ github.repository }}
outputs:
  name:
    description: The generated name of the release
    value: ${{ fromJSON(steps.notes.outputs.result).data.name }}
  body:
    description: The generated body describing the contents of the release supporting markdown formatting
    value: ${{ fromJSON(steps.notes.outputs.result).data.body }}
runs:
  using: composite
  steps:
  - id: notes
    uses: actions/github-script@v7
    with:
      github-token: ${{ inputs.token }}
      script: |
        return await github.request('POST /repos/swaglive/action-generate-release-notes/releases/generate-notes', {
          tag_name: 'v1',
          previous_tag_name: '' || undefined,
          headers: {
            'X-GitHub-Api-Version': '2022-11-28',
          },
        })
