name: Generate Release Notes

on:
  push:
  workflow_dispatch:

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate Release Notes
      uses: ./
      env:
        tag: v2
        