name: Generate Release Notes

on:
  push:
  workflow_dispatch:

jobs:
  generate-notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest

    permissions: read-all

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate Release Notes
      id: release-notes
      uses: ./
      env:
        tag: v2
    
    - run: echo '${{ steps.release-notes.outputs.name }} ${{ steps.release-notes.outputs.body }}'