name: Generate Release Notes

on:
  workflow_dispatch:

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    steps:
    - name: Generate Release Notes
      uses: ./.github/actions/release-notes
      env:
        tag: v1
        