name: Generate Release Notes

on:
  push:
  workflow_dispatch:

jobs:
  generate-notes:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # - name: Generate Release Notes
    #   uses: ./
    #   env:
    #     tag: v2

    - id: notes
      uses: actions/github-script@v7
      with:
        script: |
          return await github.request('POST /repos/swaglive/action-generate-release-notes/releases/generate-notes', {
            tag_name: 'v1',
            previous_tag_name: '' || undefined,
            headers: {
              'X-GitHub-Api-Version': '2022-11-28',
            },
          })

    - run: echo '${{ steps.notes.outputs.result }}'